# Generated by Django 5.0.3 on 2024-12-04 16:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True, verbose_name='question text')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2024, 12, 4, 16, 45, 55, 674366, tzinfo=datetime.timezone.utc), verbose_name='publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='alternative text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='polls.question')),
            ],
        ),
        migrations.AddConstraint(
            model_name='alternative',
            constraint=models.UniqueConstraint(fields=('question', 'text'), name='unique_alternative_per_question'),
        ),
    ]
