name: CI Pipeline for polls app

on:
  push:
    branches:
      - main
      - app/polls-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: create .env file
        run: |
          cd polls_project
          cat << EOF > .env
          #django
          DJANGO_SECRET_KEY=mock_secret_key
          DJANGO_DEBUG=true

          #mariadb container
          MYSQL_USER=root
          MYSQL_PASSWORD=mock_mysql_pass
          MYSQL_ROOT_PASSWORD=mock_mysql_pass
          MYSQL_DATABASE=polls_db
          EOF

          cat .env

      - name: install docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
            compose-file: "./polls_project/docker-compose.yaml"

      - name: install dependencies
        run: |
          pip install -r polls_project/requirements.txt
      
      - name: start database
        run: |
          cd polls_project
          docker compose up -d

      - name: migrate database
        run: |
          sleep 10
          cd polls_project
          python3 manage.py migrate

      - name: run tests
        run: |
          cd polls_project
          python3 manage.py test
